# Generated by Django 2.2.13 on 2020-12-27 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movieName', models.CharField(max_length=200)),
                ('Artist', models.CharField(max_length=200)),
                ('relieseDate', models.CharField(max_length=200)),
            ],
        ),
    ]
