# Generated by Django 2.2.13 on 2020-12-29 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='song1',
            field=models.FileField(blank=True, upload_to='songs/'),
        ),
        migrations.AddField(
            model_name='movies',
            name='song10',
            field=models.FileField(blank=True, upload_to='songs/'),
        ),
        migrations.AddField(
            model_name='movies',
            name='song2',
            field=models.FileField(blank=True, upload_to='songs/'),
        ),
        migrations.AddField(
            model_name='movies',
            name='song3',
            field=models.FileField(blank=True, upload_to='songs/'),
        ),
        migrations.AddField(
            model_name='movies',
            name='song4',
            field=models.FileField(blank=True, upload_to='songs/'),
        ),
        migrations.AddField(
            model_name='movies',
            name='song5',
            field=models.FileField(blank=True, upload_to='songs/'),
        ),
        migrations.AddField(
            model_name='movies',
            name='song6',
            field=models.FileField(blank=True, upload_to='songs/'),
        ),
        migrations.AddField(
            model_name='movies',
            name='song7',
            field=models.FileField(blank=True, upload_to='songs/'),
        ),
        migrations.AddField(
            model_name='movies',
            name='song8',
            field=models.FileField(blank=True, upload_to='songs/'),
        ),
        migrations.AddField(
            model_name='movies',
            name='song9',
            field=models.FileField(blank=True, upload_to='songs/'),
        ),
    ]
