# Generated by Django 2.2.13 on 2021-01-07 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boom', '0002_auto_20201229_1242'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movies',
            old_name='Artist',
            new_name='artist',
        ),
        migrations.RenameField(
            model_name='movies',
            old_name='movieName',
            new_name='movie',
        ),
        migrations.AlterField(
            model_name='movies',
            name='relieseDate',
            field=models.DateField(auto_now_add=True),
        ),
    ]
