# Generated by Django 2.2.13 on 2021-01-07 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boom', '0003_auto_20210107_1346'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Movies',
            new_name='Movie',
        ),
    ]
