# Generated by Django 2.2.13 on 2021-01-07 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boom', '0004_auto_20210107_1351'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='relieseDate',
            new_name='date',
        ),
    ]
