# Generated by Django 2.2.13 on 2021-01-07 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boom', '0005_auto_20210107_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
