# Generated by Django 2.2.13 on 2021-01-08 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boom', '0007_auto_20210108_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='movie',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='song',
            name='song_file',
            field=models.FileField(upload_to='songs/'),
        ),
    ]
