# Generated by Django 2.2.13 on 2021-01-17 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boom', '0013_auto_20210114_2156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='song',
        ),
        migrations.AddField(
            model_name='playlist',
            name='song',
            field=models.ManyToManyField(to='boom.Song'),
        ),
    ]
