# Generated by Django 2.2.13 on 2021-01-17 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boom', '0014_auto_20210117_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='song',
            field=models.ManyToManyField(blank=True, to='boom.Song'),
        ),
    ]
