# Generated by Django 2.2.13 on 2021-01-19 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boom', '0016_favourite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favourite',
            name='is_fav',
        ),
        migrations.RemoveField(
            model_name='favourite',
            name='song',
        ),
        migrations.AddField(
            model_name='favourite',
            name='song',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='boom.Song'),
        ),
    ]
